name: Code Integration To main branch

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs_on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "JDK setup"
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: "Compiling Code"
        run: mvn compile

      - name: "Running Unittests"
        run: mvn test

